### ISSUE TITLE
Service Proxies Documentation Does Not Mention Required `package-info.java` and associated annotations

### ISSUE THREAD

**Issue by InfoSec812** [vert-x3/vertx-service-proxy#101]
When writing service proxies in Vert.x, the packages where those services are created need a `package-info.java` file with appropriate annotations so that the code generation will work. In the Service Proxy docs, this is not mentioned and it should be. I would suggest adding docs around create the `package-info.java` and using the `@ModuleGen` annotation

**Comment by slinkydeveloper** [comment]
Solved by https://github.com/vert-x3/vertx-service-proxy/pull/113/files
