### ISSUE TITLE
HelperUtils loses the stacktrace of real exception

### ISSUE THREAD

**Issue by D-D-H** [vert-x3/vertx-service-proxy#103]
I found same problem at https://github.com/vert-x3/vertx-service-proxy/issues/88, and this problem should be resolved in 3.7.1, but I still encounter this problem in 3.7.1, can you help me?

**Comment by gaol** [comment]
Looks there is a `includeDebugInfo` introduced in `ServiceBinder`, have you tried to use `setIncludeDebugInfo(true)` ?

**Comment by D-D-H** [comment]
> includeDebugInfo

there is no method named setIncludeDebugInfo in io.vertx.serviceproxy.ServiceBinder

**Comment by gaol** [comment]
Ah, I see. The fix https://github.com/vert-x3/vertx-service-proxy/commit/1ec01694a82c41d15306fde956a0359337a32b06 went into `master`(4.0.0-SNAPSHOT) branch only. Are you feasible to switch to latest `4.0.0-milestone3` ? :)

**Comment by D-D-H** [comment]
Ok, I will try 4.0.0, thanks.
