### ISSUE TITLE
Build failed because removed methods used

### ISSUE THREAD

**Issue by gaol** [vert-x3/vertx-service-proxy#105]
Last master branch building failed with message:

<pre>
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project vertx-service-proxy: Compilation failure
[ERROR] /home/lgao/sources/vertx/vertx-service-proxy/src/main/java/io/vertx/serviceproxy/ServiceJWTInterceptor.java:[126,17] cannot find symbol
[ERROR]   symbol:   method isAuthorised(java.lang.String,io.vertx.core.Handler<io.vertx.core.AsyncResult<java.lang.Boolean>>)
[ERROR]   location: variable user of type io.vertx.ext.auth.User

</pre>

**Comment by pmlopes** [comment]
Fixed
