### ISSUE TITLE
Service Proxies handling Observables

### ISSUE THREAD

**Issue by brunoriscado** [vert-x3/vertx-service-proxy#11]
This is relate with issue #5, which has been closed (but incorrectly in my opinion):

previous issue: https://github.com/vert-x3/vertx-service-proxy/issues/5

While the generated proxies offer an Observable handing implementation on the client side, there is no way for the handler to put and observable (coming from the service implementation side) in the eventbus for a reply.

So right now on the service implementation side, if you're doing any operations with an Observable you need to subscribe to those observables first, so that you then pass a concrete entity class into the handler.

I'm sure it is possible to put observable in the event bus, as I've done it before using Vertx Codecs/Buffer, but I'm not entirely sure what would be the best way to do it, once you enter the realm of dealing with the proxy generated handler classes?

Are you guys going to add such a feature?

**Comment by brunoriscado** [comment]
This issue can be closed,  at the time of opening it, I obviously failed to understand how the event bus worked locally.

In any case for anyone looking for an rxjava/observable solution that works across the hazelcast eventbus, we ended up serializing our request/responses into the event bus (using any of the pre available codecs, ex: byte[] or buffer) and unwrapping/wrapping them into observable streams on each side of the handlers, as all of our services reply with Observable<?>.

It is not the most elegant solution but seems to work without a lot of fuss.

**Comment by cescoffier** [comment]
Thanks for the feedback.
