### ISSUE TITLE
Prune ServiceProxyProcessor

### ISSUE THREAD

**Issue by slinkydeveloper** [vert-x3/vertx-service-proxy#110]
Because now the annotation processor entrypoint is always "`CodegenProcessor` from vertx-codegen, we don't need this class anymore. https://github.com/vert-x3/vertx-service-proxy/blob/master/src/main/java/io/vertx/serviceproxy/generator/ServiceProxyProcessor.java#L25

**Comment by slinkydeveloper** [comment]
@vietj Can we remove it for 4.0?

**Comment by vietj** [comment]
@slinkydeveloper can you elaborate why it needs to be removed ?

**Comment by slinkydeveloper** [comment]
comment updated

**Comment by vietj** [comment]
I set deprecate because there cannot be a migration path from Vert.x 3 to Vert.x 4 if we remove the processor.

**Comment by slinkydeveloper** [comment]
It's already deprecated, this issue is meant to remind us we need to prune it :smile:

**Comment by vietj** [comment]
is it deprecated in 3.X ?

**Comment by slinkydeveloper** [comment]
Yes: https://github.com/vert-x3/vertx-service-proxy/blob/3.9/src/main/java/io/vertx/serviceproxy/generator/ServiceProxyProcessor.java#L25

**Comment by vietj** [comment]
alright then, I think what we need is update the 4.0.0 wiki page and have a step in the 4.0 migration guide

**Comment by slinkydeveloper** [comment]
Ok so together with adding a step in the migration guide, can I move forward with removing that class?

**Comment by vietj** [comment]
yes @slinkydeveloper
