### ISSUE TITLE
Wrong classloader used to load proxy classes

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-service-proxy#14]
It should use the verticle classloader and not `Class.forName` as this use the application classloader directly. In other words, it ignore all classes passed in the `-cp` parameter. It also make the service proxies unsuitable on OSGi.

https://github.com/vert-x3/vertx-service-proxy/blob/master/src/main/java/io/vertx/serviceproxy/ProxyHelper.java#L64

**Comment by vietj** [comment]
I believe we don't need this at all and we can replace the code with a `new ...EBProxy(...)` directly. Actually I think that this method should be removed because it creates more harm than good :-)

**Comment by cescoffier** [comment]
Yes, but it's a bit the chicken and egg issue with this way as when you create the class the `*EBProxy` class is not created yet, so kind of misleading. I'm not against, but it needs to be carefully documented (package and name of the class as the IDE cannot help) and be clear that an additional compilation is required (outside the IDE I guess).

**Comment by cescoffier** [comment]
In addition, there is the same issue in the `ProxyHelper` class (line 66).

**Comment by vietj** [comment]
a single compilation works, APT is designed to work this way.

**Comment by cescoffier** [comment]
I've tried in intellij and it did not work. I had to launch `mvn compile` manually.

**Comment by vietj** [comment]
I meant with Maven of course :-) . Intellij will print red until generation happens (and not necessarily compilation). In Eclipse it will work because Eclipse has an incremental compiler.

**Comment by vietj** [comment]
So we

**Comment by vietj** [comment]
sorry accidental close :-)

**Comment by cescoffier** [comment]
So, require documentation (and won't fixed the second occurrence of the bug)

**Comment by cescoffier** [comment]
Also thinking that we can completely hide this stuff (but after the 3.0 final ;-))
