### ISSUE TITLE
Allow pluggable marshallers

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-service-proxy#17]
Generated proxies currently always encode/decode the request/response to/from JSON.

This is nice and interoperable and allows services to be easily called by just sending messages directly on the event bus, but it is not necessarily very efficient.

We should abstract out the marshalling code and allow it to be pluggable. So that, for example an efficient binary encoding can be used (or whatever), if the user prefers that.

**Comment by msavy** [comment]
I wonder if it might even be possible to make this play nicely with Google's [Protocol-Buffers](https://github.com/google/protobuf) - that would be very exciting because it can generate an optimised binary format for a given input/output (and generate the marshalling/unmarshalling code). Possibly too complicated to implement for the short term. I think this could be big performance win for Vert.x.

See also:
 - https://github.com/google/protobuf
 - https://developers.google.com/protocol-buffers/
 - https://developers.google.com/protocol-buffers/docs/overview

**Comment by purplefox** [comment]
+1 no reason why any particular marshalling implementation couldn't use google protobufs if it liked

**Comment by jebbench** [comment]
Has there been any progress on this? I'd like to use Jackson for marshaling my DataObjects but with the exception of the toJson method this seems quite tricky to implement currently.

**Comment by vietj** [comment]
no progress so far as nobody has contributed or planned to contribute this feature

**Comment by diliuskh** [comment]
Hi. I was able to use service-proxy with kotlin data classes marked with `@DataObject` using [kryo](https://github.com/EsotericSoftware/kryo) library. There were some workarounds required to pull it off.
vertx-codegen requires implementation of `JsonObject toJson()`(`ProxyModel` class in codegen checks for this method, so couldn't get rid of it) method for data objects. So the method was moved to common interface with default method implementation that uses `io.vertx.core.json.Json.mapper.convertValue` internally. The public constructor with `JsonObject` argument required by `DataObjectModel` class in codegen and is used in *.templ files in vertx-service-proxy. Skipping data object proccessing during compilation solves one problem and adding modified versions of *.templ files + customized `ProxyHandler` and implementation of MessageCodec solves the other.

**Comment by diliuskh** [comment]
Perhaps adding new annotation with usage something along the lines `@ProxySerializable(MyMessageCodec.class)` would be a good start and keeping `@DataObject` as is forbackward compatibility.

**Comment by stephanebastian** [comment]
Hello,
I am interested in this topic and may contribute something once I fully understand what need to be done. Right now, we already have the interface MessageCodec<S, R> to send arbitrary Pojo to/from the event bus. Therefore I am puzzled as to what we need to do: 
* Is the goal to modify the code currently generated by the service-proxy to use a MessageCodec ? (Right now we mandate a DataObject class to define a constructor that takes a JsonObject as well as a method toJson()) 
* Or is the goal to define a different interface than MessageCodec to abstract out the (un)marshalling  ?

My opinion at that time is that it would make sens to always use a MessageCodec to send arbitrary Pojo (including DataObject) to/from the event bus. 
Any take on this ?

**Comment by vietj** [comment]
@stephanebastian  agree we should define properly the goals and non goals of this issue

**Comment by vietj** [comment]
I think the original goal is performance

**Comment by vietj** [comment]
I think that the encoding would be done externally, concerning the constructor, I think we would use the empty constructor when it's available otherwise the json constructor with an empty object

**Comment by vietj** [comment]
perhaps we can look at the event bus interceptors to implement this

**Comment by vietj** [comment]
perhaps the one thing is to define a target efficient codec for POJO that we can use and see how it can be used

**Comment by vietj** [comment]
with interceptor : basically the code would just set the object on the message and the interceptor would take care of encoding/decoding it to/from a buffer

**Comment by vietj** [comment]
btw : what I'm saying are just thoughts out loud :-)

**Comment by eutkin** [comment]
Hello. This is an example MessageCodec for an event bus for serializing an array of arguments. But there is one nuance. Event Bus does not provide information about registered user codecs.

[ObjectArrayCodec](https://gist.github.com/eutkin/7f941b51c4363cd8a7e3de27948f51d4)

**Comment by eutkin** [comment]
https://github.com/eclipse-vertx/vert.x/pull/2964

supporting me, please :)

**Comment by slinkydeveloper** [comment]
I close as it's solved by new `JsonCodec`s in vertx-codegen

**Comment by pjeziorowski** [comment]
Hello, please re-open the issue as `JsonCodecs ` does not solve the underlying problem

**Comment by mohamnag** [comment]
not sure about the `JsonCodec` but I would also see this option. I would even like to have an option of not serializing the message body at all. This is very useful for local only services to remove any overhead of serialization.
