### ISSUE TITLE
vertx service proxy exposed to eventbusbridge

### ISSUE THREAD

**Issue by qsys** [vert-x3/vertx-service-proxy#23]
As far as I understand, due to the 'header' and 'body' sent to proxies, the proxy addresses cannot be used to expose the services using an eventbusbridge. The reason being: there is no header sent.
It would be nice to have service proxies to be able to expose their address, so they can be accessed from 'outside' (using the eventbusbridge). This could probably be a switch on the `Proxygen` annotation
There may be different strategies to do this:

1. check if there is a 'header'. If not, check if the json message (body) contains a 'header' and 'body' field. If there is a header, well, that's how it's now. If there isn't, but there is a 'header' and 'body' in the message itself, things are pretty easy to 'extract'.

2. different addresses may be used for the 'exposed' and 'concealed' version - configurable in the `Proxygen` annotation again? 

3. ...?

**Comment by pmlopes** [comment]
Pull request #26 and #27 addressed this issue, you can now expose vertx-services to the eventbus and have generated JS bindings you can use with your browser, nodejs or even nashorn JVM clients.
