### ISSUE TITLE
Service proxies with pub-sub semantics

### ISSUE THREAD

**Issue by msavy** [vert-x3/vertx-service-proxy#24]
I have a use-case where I'm doing a pub-sub actions instead of 1:N send; it'd be great to have a similar style service-proxy setup.   Presently I'm just doing it the traditional way with hand-built proxy and service.

Is something that would validly come under this project, or perhaps requires a separate one? it's semantics would certainly be different with respect to error and reply handling.

**Comment by cescoffier** [comment]
I need to think about it, as it would only works for methods without results.

**Comment by msavy** [comment]
A couple of plausible possibilities that came to mind when I was thinking about it (may want to support all/some/none of them :-) ):

- Fire-and-forget semantics - this is the easy case.
- Pub-sub with an error channel. That is, pub-sub, plus a *separate* error channel that it is the responsibility of the client to call (or in this case the proxy) in the case an error needs to be reported. This, as contrasted to the standard send/reply semantics. There are a few different ways I could imagine doing this assuming it’s a valid approach.

**Comment by eutkin** [comment]
I would not give up such a function.
