### ISSUE TITLE
vertx-codegen dependency

### ISSUE THREAD

**Issue by sdhays** [vert-x3/vertx-service-proxy#41]
To define a service proxy, you need to use the ProxyGen annotation, which is actually in the vertx-codegen package which is not included as a dependency when you include the vertx-service-proxy package in your dependency. The documentation should at least clearly specify that you need to add in the vertx-codegen package to get the ProxyGen annotation; otherwise it's really not clear.

**Comment by vietj** [comment]
this dependency is used when you create one service proxy but not when you consume on, so running the proxy does not require to use the codegen jar on the classpath (it's pretty much like when one writes a polyglot api).
