### ISSUE TITLE
extends interface

### ISSUE THREAD

**Issue by FunnyDevs** [vert-x3/vertx-service-proxy#49]
Hi! I would like to extends an interface to have a set implemented methods, but i got

Error:(45, 8) java: ServiceVertxEBProxy is not abstract and does not override abstract method delete(it.hoop.server.model.BaseEntity,io.vertx.core.Handler) in it.hoop.server.service.DaoService

Is possibile to generate ProxyClass calling super methods???

**Comment by Ithildir** [comment]
It seems to work when doing something like https://github.com/Ithildir/airbot/commit/6fae41763274da56d8e270a7f52baa529146b190.

**Comment by slinkydeveloper** [comment]
Close as inactive, reopen if you need it

**Comment by ross-oreto** [comment]
I'm now running into this and tried the above fix which is based around using @VertxGen(concrete = false) on the abstract interface. This compiles fine however still produces an error when vertx looks for the proxyClass {name}VertxEBProxy of the abstract interface.
