### ISSUE TITLE
Rxified Service Proxies

### ISSUE THREAD

**Issue by michaelom** [vert-x3/vertx-service-proxy#5]
It would be great to support Rxified methods in Service Interfaces:

default:
```
  @Fluent
  MongoService insert(String collection, JsonObject document, Handler<AsyncResult<String>> resultHandler);
```

Observable:
```
  ObservableFuture<String> insert(String collection, JsonObject document);

```

Service Proxies really do reduce boilerplate but unfortunately it does not work well with vertx-rx.

**Comment by vietj** [comment]
you can already use services proxies with Rx, look at this example with JDBC:

https://github.com/vert-x3/vertx-examples/blob/master/rx-examples/src/main/java/io/vertx/example/rxjava/database/jdbc/Client.java

**Comment by vietj** [comment]
so actually this is valid, it is just that we don't generate yet an rx version for mongo, I will add it

**Comment by vietj** [comment]
now it exists : https://github.com/vert-x3/vertx-mongo-service/commit/2c9f0a1ed26d1ea181583948ef22ed2cd60b5ed8

the correct issue tracker would have been the vertx-mong-service project itself.

**Comment by michaelom** [comment]
Hi Julien,

thank you for your quick response. Your average response time is faster than my last project's JEE-Server.

My question was not specific to vertx-mongo, but I will gladly use the new snapshot. Apparently I missed the VertxGen-annotation so no rx-wrapper has been created.

Unfortunately the generated wrapper object has a few drawbacks:

- While the wrapper improves the situation on the client side (clients can now use the rx-proxy), the server side (e.g. MongoServiceImpl) still has to deal with callback-hell. My service performs calls to other "services", aggregates and filters results. That's really painful without rx-support.
- I am now bound to a concrete implementation rather than an interface. That really puts some limitations on how we can use the proxy.

**Comment by vietj** [comment]
On your first point, the implementation of the server side (MongoServerImpl) can use whatever it wants. I don't see the relationship with Rx. Can you explain with more details ?

Second point : we generate a class from an interface, the generator work this way. We could have generated an rx interface and an impl too. We chosed a class because the interface does not add much. Can you clarify what you mean by "limitations" ?

**Comment by michaelom** [comment]
For lack of an better example, let's assume we have a ProductService. While the client can interact with an Observable, the server (ProductServiceImpl) has to deal with methods like this:
```
public void find(String customerId, Handler<AsyncResult<List<JsonObject>>> resultHandler) {
```
So when implementing a service in order to provide events (actually just one) to the subscriber, I would have to deal with the resultHandler. It would be much more convenient to implement a method like this:
```
Observable<List<JsonObject>> find(String customerId);
```
That way I can invoke multiple downstream services in parallel, flatMap, merge, zip and aggregate, filter,...without having to deal with `Handler<AsyncResult<List<JsonObject>>>` or callbacks. Having both callbacks and Observables is not what we want. 
Note that I would not have to subscribe on the Observable. That could be done by the generated Proxy.

The limitations of the second point: Mocking/Testing, AOP-Proxies, Dependency Injection.
 
Hope this helps to understand my POV.

**Comment by xtermi2** [comment]
Hi,

I would also be happy to see the feature like michaelom desciped it.

thx

**Comment by brpIHDUN** [comment]
Hi , i don't see any activity on @michaelom request for past 2 years!!! 
Is it possible now to do what @michaelom explained in his last message? if yes can someone please give an example how. 
Thanks!

**Comment by vietj** [comment]
I think we should be able to generated an Rx version of the original service proxy interface that would provide hooks to implement it using RxJava, something like

```
interface Service {
   void foo(Handler<AsyncResult<String>> handler);
}
```

generates

```
class RxServiceAdapter implements Service{
   public void foo(Handler<AsyncResult<String>> handler) {
      // generated code that calls rxFoo()
   }
   public abstract String<String> rxFoo();
}
```

would that help ?

**Comment by Wei-Xia-Bose** [comment]
Struggling with this, would like to have this.
