### ISSUE TITLE
Interface and Service in groovy

### ISSUE THREAD

**Issue by underkin** [vert-x3/vertx-service-proxy#51]
Is there a sample on how to define the interface and the service in Groovy? 

Consuming from groovy seemss quite easy, but I haven't been able to define the interface and the implementeation in Groovy. 
Even just the implementation seems hard to achieve. Is that actually an option? an if so, does anyone has a pointer on how to do it ?

Kind regards

**Comment by cescoffier** [comment]
Right now the service interface can only be defined in Java.

**Comment by underkin** [comment]
Is it possible to do the implementation in Groovy, even if the interface is in Java?
Any pointer on some sample code?

**Comment by cescoffier** [comment]
Yes, you can do the implementation in Groovy as soon as you `implements` the Java interface. However, I'm not aware of an example of that.

It would be very similar to the Java example, except that the implementation would be in Groovy.

**Comment by bsbodden** [comment]
@cescoffier since JRuby can implement a Java Interface, I assume that we can also implement with Ruby?

**Comment by slinkydeveloper** [comment]
@bsbodden it should work

I close it for inactivity, reopen if you need it
