### ISSUE TITLE
proxyHandler.setConsumer(consumer) in 3.5

### ISSUE THREAD

**Issue by Sergey80** [vert-x3/vertx-service-proxy#60]
I used to have:
  MessageConsumer<JsonObject> consumer = getVertx().eventBus().<JsonObject>consumer(eventBusAddress.value()).handler(proxyHandler);
                proxyHandler.setConsumer(consumer);

when switched to 3.5 there is no setConsumer(), that is the recommendation about it?

Thanks.

**Comment by vietj** [comment]
I think now you need to use the register method that does everything in one go:

```
proxyHandler.register(getVertx().eventBus(), eventBusAddress.value());
```

later on you call `proxyHandler.unregister()`

**Comment by Sergey80** [comment]
ok. thanks.
