### ISSUE TITLE
How do I generate RX-ified service proxy?

### ISSUE THREAD

**Issue by pyctam** [vert-x3/vertx-service-proxy#62]
like for this one https://github.com/vert-x3/vertx-examples/blob/master/service-proxy-examples/service-provider/src/main/generated/io/vertx/rxjava/examples/service/ProcessorService.java

Wasn't able to see any mention of that in docs.

**Comment by BillyYccc** [comment]
You can take a look at my [demo](https://github.com/BillyYccc/vertx-postgresql-starter), the interface is like [this](https://github.com/BillyYccc/vertx-postgresql-starter/blob/master/src/main/java/com/billyyccc/database/BookDatabaseService.java) to generate RX-ified service proxy, hope this may help you.

**Comment by vietj** [comment]
thanks @BillyYccc

**Comment by vietj** [comment]
@BillyYccc how about adding your demo to the vertx awesome page ?

**Comment by BillyYccc** [comment]
@vietj I'm very glad to do this, after some optimization I will make a PR.

**Comment by BillyYccc** [comment]
😄It seems that streaming on eventBus may be supported in the next version as the roadmap shows in https://docs.google.com/presentation/d/1jIFJ3Z9APPdjU4LXPxQU8nLp8mugFYqeeZAWfVkHaAU/edit#slide=id.g32cfd27ea7_0_14. @CasterKKK

**Comment by barbarosalp** [comment]
@BillyYccc I have checked your interface and everything looks similar but rx-ified proxy was not generated. Do you have any idea what could it be?

**Comment by BillyYccc** [comment]
@barbarosalp can you give more details? a reproducer project may be better

**Comment by barbarosalp** [comment]
@BillyYccc can you please check the referenced issue above?

**Comment by BillyYccc** [comment]
@barbarosalp looks like you're missing `rx-java2-gen` dependency. Can you give a try adding
```
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-rx-java2-gen</artifactId>
    </dependency>
```

**Comment by barbarosalp** [comment]
Oh, I really did miss that. 
It works now, thanks for your help!

**Comment by BillyYccc** [comment]
:smiley: actually documentation on how to genarate rx-ified service proxy is in planning, see https://github.com/vert-x3/issues/issues/341.

**Comment by zortx233** [comment]
Thank you, I just spent the past 2 hours trying to figure out why my rx'ified service proxies weren't generating anymore when moving from Vert.x 3.5.4 to 3.7.1.
This helped me figure it out.

I find it odd that I have the explicitly specify the version because it is missing from the vertx-stack-depchain bom

**Comment by rolintoucour** [comment]
You saved my mind after few days... Thank you so much
