### ISSUE TITLE
Missing @Override annotation on methods in *VertxEBProxy

### ISSUE THREAD

**Issue by davidjirovec** [vert-x3/vertx-service-proxy#65]
In recent version of IntelliJ IDEA this warning is indicated also on the service interface annotated with `@ProxyGen`, which adds unnecessary "noise" to the code. Please generate `@Override` annotation on *VertxEBProxy methods.

**Comment by tsegismont** [comment]
Would you like to to contribute this?

**Comment by davidjirovec** [comment]
ok :)
