### ISSUE TITLE
EventBus reply exception when accessing service from vertical

### ISSUE THREAD

**Issue by idrismike** [vert-x3/vertx-service-proxy#95]
Hi, 
I have been working with Vertx services. the service runs properly but I get the following exceptions (time out):
1. from the consumerverticle, I create serviceproxy as follows:
MyService service = MyService(vertx, "vtx.myservice");
when I call a method e.g. service.getData(Handler);

The method failed to succeed after 30000(ms) - I know that the service takes time to load data, but here the client gives the following timeout exception.

io.vertx.core.eventbus.ReplyException: Timed out after waiting 30000(ms) for a reply. address: __vertx.reply.4a231290-a1b4-4aaf-8de2-0c2be3b29a40

**Comment by slinkydeveloper** [comment]
Have you tried to measure how much time the service needs to reply? btw you can configure the proxy timeout with https://vertx.io/docs/apidocs/io/vertx/core/eventbus/DeliveryOptions.html#setSendTimeout-long-

**Comment by slinkydeveloper** [comment]
Close as inactive, reopen if you need it
